// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSNo_mtnrXZHnGhmX_6K4_XYE3Dn6IhcE',
    appId: '1:829283785484:web:d27980805674ebd0cfc729',
    messagingSenderId: '829283785484',
    projectId: 'vaultx-6ecd4',
    authDomain: 'vaultx-6ecd4.firebaseapp.com',
    storageBucket: 'vaultx-6ecd4.firebasestorage.app',
    measurementId: 'G-XQEJ1Q8SBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByusN3Q_j9Ew8-OZSCibM1ZLaln9GIPcY',
    appId: '1:829283785484:android:1b4dfbb77680302acfc729',
    messagingSenderId: '829283785484',
    projectId: 'vaultx-6ecd4',
    storageBucket: 'vaultx-6ecd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBayHnEXBarmTHHSRTa_rlS2RucCrSQWM8',
    appId: '1:829283785484:ios:f801f0d07d7aed39cfc729',
    messagingSenderId: '829283785484',
    projectId: 'vaultx-6ecd4',
    storageBucket: 'vaultx-6ecd4.firebasestorage.app',
    iosBundleId: 'com.example.vaultx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBayHnEXBarmTHHSRTa_rlS2RucCrSQWM8',
    appId: '1:829283785484:ios:f801f0d07d7aed39cfc729',
    messagingSenderId: '829283785484',
    projectId: 'vaultx-6ecd4',
    storageBucket: 'vaultx-6ecd4.firebasestorage.app',
    iosBundleId: 'com.example.vaultx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSNo_mtnrXZHnGhmX_6K4_XYE3Dn6IhcE',
    appId: '1:829283785484:web:9bfc40a3bffffdd5cfc729',
    messagingSenderId: '829283785484',
    projectId: 'vaultx-6ecd4',
    authDomain: 'vaultx-6ecd4.firebaseapp.com',
    storageBucket: 'vaultx-6ecd4.firebasestorage.app',
    measurementId: 'G-LCPZZDFZK9',
  );
}
